scheme: http
hostname: localhost
reverse-proxy-port: 7080
reverse-proxy-uri: ${scheme}://${hostname}:${reverse-proxy-port}
authorization-server-prefix: /auth
issuer: ${reverse-proxy-uri}${authorization-server-prefix}/realms/springbootexample
client-id: spring-boot-example
client-secret: IwIFSWS4L4alqhiZN6gfiGcmPDOlxMKk
authorities-json-path: $.realm_access.roles
bff-port: 7081
bff-prefix: /bff
resource-server-port: 7084

server:
  port: ${bff-port}
spring:
  application:
    name: bff
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: bff
              uri: ${scheme}://${hostname}:${resource-server-port}
              predicates:
                - Path=/api/**
              filters:
                - TokenRelay=
                - SaveSession
                - StripPrefix=1
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${issuer}
        registration:
          springbootexample:
            provider: keycloak
            client-id: ${client-id}
            client-secret: ${client-secret}
            authorization-grant-type: authorization_code
            scope: openid,profile,email,offline_access
com:
  c4-soft:
    springaddons:
      oidc:
        ops:
          - iss: ${issuer}
            authorities:
              - path: ${authorities-json-path}
        client:
          client-uri: ${reverse-proxy-uri}${bff-prefix}
          security-matchers:
            - /api/**
            - /login/**
            - /oauth2/**
            - /logout/**
          permit-all:
            - /api/**
            - /login/**
            - /oauth2/**
            - /logout/connect/back-channel/springbootexample
          post-logout-redirect-host: ${hostname}
          csrf: cookie_accessible_from_js
          oauth2-redirections:
            rp-initiated-logout: accepted
          back-channel-logout:
            enabled: true
            internal-logout-uri: ${scheme}://${hostname}:${bff-port}/logout
        resourceserver:
          permit-all:
            - /login-options